#!/usr/bin/env python3
import requests
import sys

URL = "https://qrng.anu.edu.au/API/jsonI.php?length={length}&type=uint8"
HEADERS = {"Content-Type": "application/json"}


def main(length):
    url = URL.format(length=length)
    r = requests.post(url, headers=HEADERS)
    r.raise_for_status()

    pxs = r.json()

    res = [str(i) for i in pxs['data']]

    return " ".join(res)


if __name__ == "__main__":
    try:
        print(main(sys.argv[1]))
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)