#!/usr/bin/env python3
import requests
import sys

URL = "https://api-osmosis.imperator.co/tokens/v2/{token}"
HEADERS = {"Content-Type": "application/json"}


def main(token):
    url = URL.format(token=token)
    r = requests.get(url, headers=HEADERS)
    r.raise_for_status()

    pxs = r.json()

    res = pxs[0]['price']

    return res


if __name__ == "__main__":
    try:
        print(main(sys.argv[1]))
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)